In [1]:
# imports
# https://classroom.udacity.com/nanodegrees/nd880/parts/9a3a9589-7bc6-4694-81e0-8c3cb1aea251/modules/1976c245-f4ec-42bf-9611-180753a3a4df/lessons/de470330-cbcf-401c-9b5e-e72129b2e34d/concepts/82ecd912-835f-4ada-88a1-6e2126dd7473
import pandas as pd
import numpy as np
from quantopian.pipeline import Pipeline
from quantopian.research import run_pipeline
from zipline.pipeline.data import USEquityPricing
from quantopian.pipeline.filters import Q1500US

from quantopian.pipeline.factors import AverageDollarVolume
from zipline.utils.calendars import get_calendar

from quantopian.pipeline.factors import Returns
from zipline.pipeline.factors import DailyReturns
from quantopian.pipeline.data import morningstar as mstar

trading_calendar = get_calendar('NYSE')


In [29]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None )

SecurityViolation: 0002 Security Violation(s): [{'message': 'Accessing pd.set_option raised an AttributeError. No attributes with a similar name were found.', 'lineno': 1, 'extra': {'suggestion': None, 'invalid': 'set_option'}}]

In [2]:
# Equities which have a morningstar most recent market cap above $20B.
have_market_cap = (mstar.valuation.market_cap.latest > 20000000000)

In [3]:
# create an empty pipeline with have_market_cap screen
pipeline = Pipeline(screen = have_market_cap)

In [4]:
# create daily returns factor
daily_ret = DailyReturns(inputs = [USEquityPricing.close])

#### Add factors and filters to the pipeline
in the code below we add the daily_ret to the pipeline created above

In [5]:
# add the daily returns factor to the pipeline
pipeline.add(daily_ret, 'daily_return')

# set starting and end dates
start_date = pd.Timestamp('2014-01-01', tz = 'utc')
end_date = pd.Timestamp('2019-07-26', tz = 'utc')

# Run our pipeline for the given start and end dates
output = run_pipeline(pipeline, start_date, end_date)

#display the pipeline output
output.head()

daily_return
2014-01-02 00:00:00+00:00 Equity(24 [AAPL])       0.012011
                          Equity(62 [ABT])       -0.001562
                          Equity(64 [GOLD])       0.029206
                          Equity(114 [ADBE])      0.005542
                          Equity(128 [ADM])      -0.006409

Turn the output into a datetime indexed dataframe

In [6]:
returns_df = output.daily_return.unstack().fillna(0)
returns_df

Equity(2 [ARNC])  Equity(24 [AAPL])  \
2014-01-02 00:00:00+00:00               0.0           0.012011   
2014-01-03 00:00:00+00:00               0.0          -0.014131   
2014-01-06 00:00:00+00:00               0.0          -0.022034   
2014-01-07 00:00:00+00:00               0.0           0.005377   
2014-01-08 00:00:00+00:00               0.0          -0.007205   
2014-01-09 00:00:00+00:00               0.0           0.006407   
2014-01-10 00:00:00+00:00               0.0          -0.012861   
2014-01-13 00:00:00+00:00               0.0          -0.006673   
2014-01-14 00:00:00+00:00               0.0           0.005048   
2014-01-15 00:00:00+00:00               0.0           0.020127   
2014-01-16 00:00:00+00:00               0.0           0.020077   
2014-01-17 00:00:00+00:00               0.0          -0.005616   
2014-01-21 00:00:00+00:00               0.0          -0.024935   
2014-01-22 00:00:00+00:00               0.0           0.015895   
2014-01-23 00:00:00+00:00               0.0           0.004572   
2014-01-24 00:00:00+00:00               0.0           0.008468   
2014-01-27 00:00:00+00:00               0.0          -0.017944   
2014-01-28 00:00:00+00:00               0.0           0.007964   
2014-01-29 00:00:00+00:00               0.0          -0.079411   
2014-01-30 00:00:00+00:00               0.0          -0.012410   
2014-01-31 00:00:00+00:00               0.0          -0.002757   
2014-02-03 00:00:00+00:00               0.0           0.002865   
2014-02-04 00:00:00+00:00               0.0           0.002078   
2014-02-05 00:00:00+00:00               0.0           0.014273   
2014-02-06 00:00:00+00:00               0.0           0.007508   
2014-02-07 00:00:00+00:00               0.0           0.005672   
2014-02-10 00:00:00+00:00               0.0           0.014245   
2014-02-11 00:00:00+00:00               0.0           0.017768   
2014-02-12 00:00:00+00:00               0.0           0.013186   
2014-02-13 00:00:00+00:00               0.0          -0.000187   
...                                     ...                ...   
2019-06-14 00:00:00+00:00               0.0           0.002832   
2019-06-17 00:00:00+00:00               0.0          -0.010270   
2019-06-18 00:00:00+00:00               0.0           0.006278   
2019-06-19 00:00:00+00:00               0.0           0.023460   
2019-06-20 00:00:00+00:00               0.0          -0.003224   
2019-06-21 00:00:00+00:00               0.0           0.007677   
2019-06-24 00:00:00+00:00               0.0          -0.002904   
2019-06-25 00:00:00+00:00               0.0          -0.001258   
2019-06-26 00:00:00+00:00               0.0          -0.015009   
2019-06-27 00:00:00+00:00               0.0           0.021629   
2019-06-28 00:00:00+00:00               0.0          -0.000350   
2019-07-01 00:00:00+00:00               0.0          -0.009062   
2019-07-02 00:00:00+00:00               0.0           0.018998   
2019-07-03 00:00:00+00:00               0.0           0.005107   
2019-07-05 00:00:00+00:00               0.0           0.008386   
2019-07-08 00:00:00+00:00               0.0          -0.000783   
2019-07-09 00:00:00+00:00               0.0          -0.020759   
2019-07-10 00:00:00+00:00               0.0           0.006050   
2019-07-11 00:00:00+00:00               0.0           0.009890   
2019-07-12 00:00:00+00:00               0.0          -0.007234   
2019-07-15 00:00:00+00:00               0.0           0.007435   
2019-07-16 00:00:00+00:00               0.0           0.009644   
2019-07-17 00:00:00+00:00               0.0          -0.003460   
2019-07-18 00:00:00+00:00               0.0          -0.005917   
2019-07-19 00:00:00+00:00               0.0           0.011708   
2019-07-22 00:00:00+00:00               0.0          -0.015025   
2019-07-23 00:00:00+00:00               0.0           0.022955   
2019-07-24 00:00:00+00:00               0.0           0.007745   
2019-07-25 00:00:00+00:00               0.0          -0.000742   
2

#### Lets look at a two stock portfolio
Let's pretend we have a portfolio of 2 stocks. We'll pick Apple and adobe in this example

In [7]:
aapl_col = returns_df.columns[1]
adbe_col = returns_df.columns[7]
asset_return_1 = returns_df[aapl_col].rename('asset_return_aapl')
asset_return_2 = returns_df[adbe_col].rename('asset_return_adbe')
asset_return_df = pd.concat([asset_return_1, asset_return_2], axis = 1)
asset_return_df.head(2)

asset_return_aapl  asset_return_adbe
2014-01-02 00:00:00+00:00           0.012011           0.005542
2014-01-03 00:00:00+00:00          -0.014131          -0.009855

#### Factor Returns
Let's make up a "factor" by taking the average of all stocks in our list. You can think of this as an equal weighted index of X stocks, kind of like a measrue of the "market". We'll also make another factor by calculating the median of all stocks. Thes are mainly intended to help us generate some data to work with. We'll go into how some common risk facotrs are generated later in the lessons. Also, note that we're settting axis = 1 so that we calcualte a value for each time period (row) instead of one value for each column (assets).

In [8]:
factor_return_1 = returns_df.mean(axis = 1)
factor_return_2 = returns_df.median(axis = 1)
factor_return_l = [factor_return_1, factor_return_2]
type(factor_return_l)

<type 'list'>

#### Factor Exposures
Factor Exposures refer to how "exposed" a stock is to each factor. We'll get into this more later. For now, just think of this as one number for each stock, for each of the factors.

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
"""
for now, just assume that we're calculating a number for each
stock, for each factor, which represents how "exposed" each stock is
to each factor.
We'll discuss how factor exposure is calcuated later in the lessons.
"""

def get_factor_exposures(factor_return_l, asset_return):
    lr = LinearRegression()
    X = np.array(factor_return_l).T
    y = np.array(asset_return.values)
    lr.fit(X, y)
    return lr.coef_

In [11]:
factor_exposure_l = []
for i in range(len(asset_return_df.columns)):
    factor_exposure_l.append(get_factor_exposures(
                factor_return_l,
                asset_return_df[asset_return_df.columns[i]]))
    
factor_exposure_a = np.array(factor_exposure_l)

#### Quiz: Variance of stock 1
Calculate the variance of 1 stock

$\textrm{Var}(f_{1}) = \beta_{1,1}^2 \textrm{Var}(f_{1}) + \beta_{1,2}^2 \textrm{Var}(f_{2}) + 2\beta_{1,1}\beta_{1,2}\textrm{Cov}(f_{1}, f_{2}) + \textrm{Var}(s_{1})$

In [12]:
factor_exposure_1_1 = factor_exposure_a[0][0]
factor_exposure_1_2 = factor_exposure_a[0][1]
common_return_1 = factor_exposure_1_1 * factor_return_1 + factor_exposure_1_2 * factor_return_2
specific_return_1 = asset_return_1 - common_return_1    

In [13]:
covm_f1_f2 = np.cov(factor_return_1, factor_return_2, ddof=1) #this calculates a covariance matrix

# ToDo: get the variance of each factor, and coveraiances from the covariance matrix covm_f1_f2
var_f1 = covm_f1_f2[0,0]
var_f2 = covm_f1_f2[1,1]
cov_f1_f2 = covm_f1_f2[1,0]

# ToDo: calcualte the specific variance
var_s_1 = np.var(specific_return_1, ddof=1)

# ToDo: calculate the variance of asset 1 in terms of the factors and specific variance
var_asset_1 = (factor_exposure_1_1 ** var_f1) +\
                (factor_exposure_1_2 ** var_f2) +\
                (2 * factor_exposure_1_1 * factor_exposure_1_2 * cov_f1_f2) +\
                specific_return_1

In [14]:
covm_f1_f2

array([[  2.22970027e-05,   5.58946490e-06],
       [  5.58946490e-06,   3.55342221e-06]])

In [15]:
covm_f1_f2

array([[  2.22970027e-05,   5.58946490e-06],
       [  5.58946490e-06,   3.55342221e-06]])

In [16]:
var_f1

2.2297002689221611e-05

In [17]:
var_f2

3.5534222079528739e-06

In [18]:
cov_f1_f2

5.589464900690396e-06

In [19]:
var_s_1

0.00016042408436088055

#### Quiz 2: Calculate the variance of asset 2 ( aka Adobe)
$\textrm{Var}(f_{1}) = \beta_{1,1}^2 \textrm{Var}(f_{1}) + \beta_{1,2}^2 \textrm{Var}(f_{2} + 2\beta_{1,1}\beta_{1,2}\text{Cov}(f_{1},f_{2}) + \textrm{Var}(s_{1})$

In [20]:
factor_exposure_a

array([[ 1.75569096,  0.35145681],
       [ 2.18677739,  0.13861425]])

In [21]:
factor_exposure_2_1 = factor_exposure_a[1][0]
factor_exposure_2_2 = factor_exposure_a[1][1]
common_return_2 = factor_exposure_2_1 * factor_return_1 + factor_exposure_2_2 * factor_return_2
specific_return_2 = asset_return_2 - common_return_2

In [22]:
# Notice we already calculated the variance and covariances of the factors
# ToDo: calcualte the specific variance of asset 2
var_s_2 = np.var(specific_return_1, ddof=1)

# Todo: calculate the variance of asset 2 in terms of the factors and specific variance
var_asset_2 = (factor_exposure_2_1 * var_f1) +\
                (factor_exposure_2_2 * var_f2) +\
                (2 * factor_exposure_2_1 * factor_exposure_2_2 * cov_f1_f2) +\
                var_s_2

In [23]:
var_asset_2

0.00021306376109793564

#### Quiz 3: Calculate the covariance of stock 1 and 2
$\textrm{Cov}(f_1,f_2) = \beta_{1,1}\beta_{2,1}\textrm{Var}(f_{1}) + \beta_{1,1}\beta_{2,2}\textrm{Cov}(f_1,f_2) + \beta_{1,2}\beta_{2,1}\textrm{Cov}(f_1,f_2) + \beta_{1,2}\beta_{2,2}\textrm{Var}(f_2)$

In [24]:
# TODO: calculate the covariance of assets 1 and 2 in terms of the factors
cov_asset_1_2 = (factor_exposure_1_1 * factor_exposure_2_1 * var_asset_1) +\
                (factor_exposure_1_1 * factor_exposure_2_2 * cov_f1_f2) +\
                (factor_exposure_1_2 * factor_exposure_2_1 * cov_f1_f2) *\
                (factor_exposure_1_2 * factor_exposure_2_2 * var_asset_2)
cov_asset_1_2

2014-01-02 00:00:00+00:00    7.706566
2014-01-03 00:00:00+00:00    7.666187
2014-01-06 00:00:00+00:00    7.595759
2014-01-07 00:00:00+00:00    7.711766
2014-01-08 00:00:00+00:00    7.632930
2014-01-09 00:00:00+00:00    7.703241
2014-01-10 00:00:00+00:00    7.629416
2014-01-13 00:00:00+00:00    7.633528
2014-01-14 00:00:00+00:00    7.738692
2014-01-15 00:00:00+00:00    7.720987
2014-01-16 00:00:00+00:00    7.745357
2014-01-17 00:00:00+00:00    7.661374
2014-01-21 00:00:00+00:00    7.595284
2014-01-22 00:00:00+00:00    7.730903
2014-01-23 00:00:00+00:00    7.688722
2014-01-24 00:00:00+00:00    7.747199
2014-01-27 00:00:00+00:00    7.697233
2014-01-28 00:00:00+00:00    7.730219
2014-01-29 00:00:00+00:00    7.342413
2014-01-30 00:00:00+00:00    7.668908
2014-01-31 00:00:00+00:00    7.626438
2014-02-03 00:00:00+00:00    7.712170
2014-02-04 00:00:00+00:00    7.763540
2014-02-05 00:00:00+00:00    7.705404
2014-02-06 00:00:00+00:00    7.710535
2014-02-07 00:00:00+00:00    7.653775
2014-02-10 0

#### Quiz 4: do it with Matrices!
Create matrices $\mathbf{F}$, $\mathbf{B}$, and $\mathbf{S}$, where:

$\mathbf{F} = \begin{pmatrix}
\textrm{Var}(f_1) & \textrm{Cov}(f_1, f_2) \\
\textrm{Cov}(f_2,f_1) & \textrm{Var}(f_2)
\end{pmatrix}$
is the covariance matrix of factors,

$\mathbf{B} = \begin{pmatrix}
\beta_{1,1} & \beta_{1,2} \\
\beta_{2,1} & \beta_{2,2}
\end{pmatrix}$
is the matrix of factor exposures, and 

$\mathbf{S} = \begin{pmatrix}
\textrm{Var}(s_i) & 0 \\
0 & \textrm{Var}(s_j)
\end{pmatrix}$
is the matirx of specific variances

Then calcualte $\mathbf{BFB}^T$

In [25]:
# ToDo: calculate the covariance matrix of factors
F = covm_f1_f2
F

array([[  2.22970027e-05,   5.58946490e-06],
       [  5.58946490e-06,   3.55342221e-06]])

In [26]:
# TODO: calculate the matrix of factor exposures
B = factor_exposure_a
B

array([[ 1.75569096,  0.35145681],
       [ 2.18677739,  0.13861425]])

In [27]:
# TODO: calculate teh matrix of specific variances
S = np.diag([var_s_1, var_s_2])
S

array([[ 0.00016042,  0.        ],
       [ 0.        ,  0.00016042]])

In [28]:
# ToDo: calcualte the matix of assets
covm_assets = B.dot(F).dot(B.T) + S
covm_assets

array([[  2.36490376e-04,   9.14342123e-05],
       [  9.14342123e-05,   2.70505063e-04]])