# Concept 1 - Lesson 7
## Momentum Trading - Dtype

### Dtype Object
Let's look into how you might generate positions from signals. To do that, we first need to know about `dtype` or dta type object in Numpy.

A [data_type_object](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html) is a class that irepresents the data. It's similar to a `data type` but contains [more information](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html) about the data. Let's see an example of a data type object in Numpy using the `array`.

In [1]:
import numpy as np
array = np.arange(10)

print(array)
print(type(array))
print(array.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32


From this we see `array` is a `numpy.ndarray` with the data `[0 1 2 3 4 5 6 7 8 9]` represented as `int64` (64-bit integer).

Let's see what happens when we divide the data by 2 to generate not integer data

In [2]:
float_arr = array / 2

print(float_arr)
print(type(float_arr))
print(float_arr.dtype)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
<class 'numpy.ndarray'>
float64


The array returned has the values `[0. 0.5 1. 2. 2.5 3. 3.5 4. 4.5]`, which is what you would expect for dividing by 2. However, since this data can't be represent by integers, the array is now represented as `float64` (64-bit float).

How would we convert this back to `int64`? We'll use the `ndarray.astype` function to cast it from it's current type to the type of `int64` `(np.int64)`.

In [4]:
int_arr = float_arr.astype(np.int64)

print(int_arr)
print(type(int_arr))
print(int_arr.dtype)

[0 0 1 1 2 2 3 3 4 4]
<class 'numpy.ndarray'>
int64


This casts teh dat to `int64`, but also changes the data. Since fractions can't be represented as integers, the decimal place is dropped.

### Signals to Positions
Now that you've seen how the [data type object](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html) is used in Numpy, let's see how to use it to generate positions from signals. Let's use `prices` array to represent the prices in dollars over time for a single stock.

In [5]:
prices = np.array([1,3,-2,9,5,7,2])
prices

array([ 1,  3, -2,  9,  5,  7,  2])

For the positions lset's say we want ot buy one share of stock when the price is above 2 dollars and then buy 3 more shares when it's above 4 dollars. We'll first need to generate the signal for these two positions.

In [6]:
signal_one = prices>2
signal_three = prices>4

print(signal_one)
print(signal_three)

[False  True False  True  True  True False]
[False False False  True  True  True False]


Now we multiply each array by the respective amount to invest.

In [7]:
pos_one = 1 * signal_one
pos_three = 3 * signal_three

print(pos_one)
print(pos_three)

[0 1 0 1 1 1 0]
[0 0 0 3 3 3 0]


if we add them together, we have the final position of the stock over time.

In [9]:
long_pos = pos_one + pos_three
print(long_pos)

[0 1 0 4 4 4 0]


### Quiz
Using this information, implement `generate_positions` using Pandas `df.astype` function to convert `prices` to final positions using the following signals:

- long 30 shares of stock when the price is above 50 dollars
- short 10 shares of stock when it's below 20 dollars

In [ ]:
def generate_positions(prices):
    """
    Generate the following signals:
    - long 30 shares of stock when the price is above 50 dollars
    - short 10 shares of stock when the price is below 20 dollars
    
    Parameters
    ----------
    price : DataFrame
        prices for each ticker and date
        
    REturns
    -------
    final_positions : DataFrame
        final positions for each ticker and date
    """
    
    # Todo: Implement Function
    signal_one = prices > 50
    signal_two = prices < 20
    
    signal_one = signal_one.astype(np.int)
    signal_two = signal_two.astype(np.int)
    
    pos_one = prices * 30
    pos_two = prices * -10
    
    return pos_one + pos_tow